@startuml C4_Component_Device
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(app_api, "API Gateway", "Go", "Единая точка входа, аутентификация, маршрутизация")

System_Boundary(device_boundary, "Управление устройствами") {
    Component(device_api, "API", "HTTP", "Внешний API для работы с устройствами")
    Component(device_command, "Сервис для обработки", "Go", "Обработчик команд управления")
    Component(device_registry, "Сервис для регистрации устройств", "Go", "Реестр устройств и их статусов")
    Component(device_provisioning, "Сервис для самостоятельной регистрации устройств", "Go", "Самостоятельная регистрация устройств")
    Component(device_validation, "Валидатор", "Go", "Валидация устройств и совместимости")
    Component(device_event, "Продюсер", "Go", "Публикация событий устройств")
}

ContainerDb(device_db, "База устройств", "PostgreSQL", "Профили устройств, настройки, привязка")
ContainerQueue(message_broker, "Брокер сообщений", "Kafka")


Rel(device_api, device_command, "Передает команды", "HTTP")
Rel(device_api, device_registry, "Запросы статуса", "HTTP")
Rel(device_api, device_provisioning, "Регистрация новых устройств", "HTTP")
Rel(device_command, device_registry, "Обновление статуса", "in-mem")
Rel(device_provisioning, device_validation, "Проверка совместимости", "sync")
Rel(device_registry, device_event, "Публикует изменения", "async")
Rel(device_event, message_broker, "События устройств", "AMQP")
Rel(device_registry, device_db, "Сохраняет состояние", "SQL")
Rel(device_provisioning, device_db, "Сохраняет метаданные", "SQL")
Rel(app_api, device_api, "Отправка запросов клиента", "HTTP")

@enduml